{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vllm-latency-metrics.fullname" . }}-proxy
  labels:
    {{- include "vllm-latency-metrics.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
