apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-cache
  namespace: vllm
  labels:
    app.kubernetes.io/component: vllm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
